title: తెలుగు దినపత్రిక
description: తాజా వార్తలు మరియు సమాచారం
lang: te
url: "https://yourusername.github.io"
baseurl: ""

# Jekyll settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Telugu specific
encoding: UTF-8
timezone: Asia/Kolkata
